language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm run build
deploy:
  - provider: s3
    access_key_id:
      secure: Va5B9T0/C6PJBxryOyAH+YvsDRiwl2l2xBIMM6WkwAIp9DLSv4vALd2rS7Rx2hV4qHjuRjIJwJwWce0nebBkYhXxraIFUMApA4SnlbleIJCbOFszrxX11FB+ZpQbt3zmr3XQkTQIoQPY2g4LaKamkAecUm7VYLtyob4j7gz5HU9RQpDE4IWmC4C2JBEoUcTDl3qaB2kgPZeY+cOjvPVN8v3hWjUu6jf11416lPsys2ik5DhjV8zfvr39Gk49FtXMRkFN4bxX3B1tUben73O0TV2qaHDzzCVDtK79HwIVOfPAF7kkUPd4RaLEMMoGzVBPDgWz/CvQlPbrH2aFwqfnrGH8+Y9ZRVt6jITiU9Ho4Da2re3AaNDfRF54CuIUM/N+QyIG9YxyhiU5TmzEBvYWWfOAJt7+WC+Q6nDjZzEzA0Nkn/BEqBjwm+VeNCXSMERQKVKyaTMPgo6oiuQwDxv2EvxiL0N2xbYspQNJ4JR1UM9RI++Si3XXP5ixgFPNd5jPz8AJ9omAC5fIXDtDzR0nHjrQUTPRmXj5PgD4uLmXj6+6AUDXbSIcyVCN8c6iqXtn+qMdcsSQAnZBenc0imE4Kzic0L1P8sqPZG97W15hq7zlVqqCJvoqCLdcVi3hWlBRIAUKK5ORZ05K0UXmQvLaQgDT/2y/d9i+pSx07l15ez0=
    secret_access_key:
      secure: OcSQAYiNAGFNBmjEfR3AKWLMNTbCqhzwdf/uOqzOcbknEytsyvpBNmwob5LA4z37sMRN9jT95eLLMLVLfewgAh+xaBJInvT679ED4iRzJ8X93QLyBWrYzg5Pb6ABuQmJo7CeEdIEyICeJ6leRr9+APr7sdNLxZtq/l9ECf741osiiPTNvjUco1WcOP0RLHh5PPWsJj5pnvVbay2RIQZaBffzr2ojX+cKj6G4xiMsvOx8GzB/AD8l9OUY2KuHyivriG69LnyC7rTdOibPH3scuAcFRQ6dHb+uDqaZuy6ohmXhaXwblTl3uXTTsghXh02p1jkXaMazQ5CR6myJ1e+tD5EzrMLaf5dklDdjkhumNbXx5o5MVp42htrMmHaU9z+/b5mRnBR/JIQhIqTPIqSwK3xzUpnm/cVX0CGFQHIcsqjAtr+yCG5o2wNLH0ceun/cTjN5htaxDj5zIAYVxKlp1xBURkNK7sB0ygG9E/4lIGz7dxHdo5CNlicCg/71NYlXUNO1/Y3+laaNQ9UOwSpKmdF76+IMnaFNiEj9HDV9CHklN8wvLUs6LovOKsh07VCns/18FP3HpGGzw61La+dXkgtqvsj3EHcgf+F0QhcCA4hfnzYSPOwU8VohBqz2mganDKNI8iJSBwLVmdxUDajsr8BsZgzNK4qmJPi+rmieZ7M=
    bucket: adventurio-admin-site-dev
    skip_cleanup: true
    local_dir: build
    on:
      branch: dev
